apiVersion: v1
kind: Service
metadata:
  name: astro
spec:
  selector:
    app: astro
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
  type: {{ .Values.service.type }}
