apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/headless-commerce-company-weframe-tech/strapi-poc-deployment.git
    targetRevision: HEAD
    path: charts/mariadb
  destination:
    server: https://kubernetes.default.svc
    namespace: ed-data
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
