apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3306
  type: {{ .Values.service.type }}
